# Задание на повторение материала

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [1]:
import numpy as np

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.


In [3]:
a.shape

(12,)

In [4]:
b = []
for i in [2, 3, 4, 6, 12]:
    y = 12 // i
    b.append(a.reshape((i, y)))
for b_i in b:
    print(b_i.shape)
    print(b_i)

(2, 6)
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(3, 4)
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
(4, 3)
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
(6, 2)
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
(12, 1)
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [5]:
b = [[]] * 5
# for i in [2, 3, 4, 6, 12]:
#     b.append(a.reshape((i, -1)))

b[0] = a.reshape((2, -1))
b[1] = a.reshape((4, -1))
b[2] = a.reshape((6, -1))
b[3] = a.reshape((-1, 4))
b[4] = a.reshape((-1, 1))

for b_i in b:
    print(b_i.shape)
    print(b_i)

(2, 6)
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 3)
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
(6, 2)
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
(3, 4)
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
(12, 1)
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


In [6]:
b[-1].shape

(12, 1)

С точки зрения Numpy - нет, массив b 2-мерный (если 1-мерный $\Rightarrow$ shape == (12,) т.е. только 1 ось индексирования)

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [7]:
a = np.random.randn(3, 4) # по умолчанию E=0, sigma=1
a

array([[-1.80013796,  0.35154828,  0.15299165,  0.75916586],
       [ 0.40058496,  1.98296446,  2.04127343,  0.44133731],
       [-0.92431207, -1.97443008, -1.20173396, -0.41144934]])

In [8]:
a = a.flatten()
a

array([-1.80013796,  0.35154828,  0.15299165,  0.75916586,  0.40058496,
        1.98296446,  2.04127343,  0.44133731, -0.92431207, -1.97443008,
       -1.20173396, -0.41144934])

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.


In [9]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?


In [10]:
b = np.expand_dims(a, axis=0) # из-за того, что интервал == 2, элементы массивов будут =
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [11]:
# а вот размерности и формы массивов - разные (если я правильно поняла задание)
a.shape, b.shape

((10,), (1, 10))

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.


In [12]:
# 10 = b * (a + a + 1) = b * (2 * a + 1) (второй множитель нечетный, значит первый д.б. четным, 
# a, b - целые, значит, вариантов не много: (b, 2 * a + 1) = (1, 10) or (2, 5), значит b == 2, a == 2)
a = np.zeros((2, 2))
b = np.ones((a.shape[0]+1, a.shape[1]))
c = np.vstack([a, b])
c, c.size

(array([[0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]),
 10)

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [13]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
A = np.reshape(a, (4, 3))
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [16]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [17]:
# (4, 3) @ (3, 4) = (4, 4)
B.shape

(4, 4)

In [18]:
# Т.к. матрица квадратная, то можно попробовать вычислить обратную:
import sys
try:
    np.linalg.inv(B)
except:
    print('err: ' + str(sys.exc_info()))

err: (<class 'numpy.linalg.LinAlgError'>, LinAlgError('Singular matrix'), <traceback object at 0x7f0ff01fe280>)


In [19]:
# Пишет, что матрица вырожденная (Singular matrix), т.е. ее определитель == 0. Проверим:
np.linalg.det(B)

0.0

Значит, не найти обратную :)

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.


In [20]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [21]:
c = np.random.randint(0, 16, size=(16,))
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [22]:
C = np.reshape(c, (4, 4))
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [23]:
D = B + 10 * C
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [24]:
np.linalg.det(D)

-28511999.999999944

In [25]:
np.linalg.matrix_rank(D)

4

In [26]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [27]:
D_inv[D_inv > 0] = 1
D_inv

array([[ 1.        ,  1.        ,  1.        , -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  1.        ],
       [-0.00356692, -0.01782828, -0.04152146,  1.        ],
       [ 1.        , -0.00181818,  1.        , -0.01090909]])

In [28]:
D_inv[D_inv < 0] = 0
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [30]:
np.unique(D_inv)

array([0., 1.])

In [31]:
E = np.where(D_inv, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])